User.create!(name: 'Maddy', username: 'mrombes', password: '123')

Metric.create!(name: 'Finance')
Metric.create!(name: 'Love Life')
Metric.create!(name: 'Friends & Family')
Metric.create!(name: 'Work')
Metric.create!(name: 'Creativity')
Metric.create!(name: 'Exercise')
Metric.create!(name: 'Healthy Eating')
Metric.create!(name: 'Spirituality / Self')

Rating.create!(rating: 5, user_id: 1, metric_id: 1)
Rating.create!(rating: 5, user_id: 1, metric_id: 2)
Rating.create!(rating: 5, user_id: 1, metric_id: 3)
Rating.create!(rating: 5, user_id: 1, metric_id: 4)
Rating.create!(rating: 5, user_id: 1, metric_id: 5)
Rating.create!(rating: 5, user_id: 1, metric_id: 6)
Rating.create!(rating: 5, user_id: 1, metric_id: 7)
Rating.create!(rating: 5, user_id: 1, metric_id: 8)